module Autocad
  class Arc < Element
    def length: () -> untyped

    def start_point: () -> untyped

    def end_point: () -> untyped

    def start_angle: () -> untyped

    def end_angle: () -> untyped

    def total_angle: () -> untyped
  end
end
