module Autocad
  Error: untyped

  NonDGNFile: untyped

  FileNotFound: untyped

  MultipleUpdateError: untyped

  class DrawingError < Error
    @drawing: untyped

    attr_reader drawing: untyped

    def initialize: (untyped message, untyped drawing) -> void
  end

  class ExistingFile < Error
    def initialize: (untyped path) -> void
  end
end
