module Autocad
  class Line < Element
    def length: () -> untyped

    def start_point: () -> untyped

    def end_point: () -> untyped
  end

  class Polyline < Element
    def length: () -> untyped

    def coordinates: () -> untyped
  end
end
