class Person
  @name: untyped

  @addresses: untyped

  attr_reader name: untyped

  attr_reader addresses: untyped

  # @rbs name: String
  # @rbs addresses: Array[String]
  # @rbs return: void
  def initialize: (name: untyped, addresses: untyped) -> void

  def to_s: () -> ::String

  # @rbs &block: (String) -> void
  def each_address: () { (?) -> untyped } -> untyped
end
