module Autocad
  class Point3d
    @x: untyped

    @y: untyped

    @z: untyped

    def self.cartesian_to_polar: (untyped x, untyped y) -> ::Array[untyped]

    def self.from_polar_degrees: (untyped r, untyped a) -> nil

    def self.from_ole: (untyped ole) -> untyped

    def self.polar_to_cartesian: (untyped r, untyped a) -> nil

    attr_reader x: untyped

    attr_reader y: untyped

    attr_reader z: untyped

    def initialize: (?untyped? _x, ?untyped? _y, ?untyped? _z, ?x: untyped, ?y: untyped, ?z: untyped) -> void

    def +: (untyped other) -> untyped

    def deconstruct: () -> ::Array[untyped]

    def deconstruct_keys: () -> { x: untyped, y: untyped, z: untyped }

    def to_ary: () -> ::Array[untyped]

    def -: (untyped other) -> untyped

    def to_s: () -> ::String

    def to_a: () -> ::Array[untyped]

    def zero: () -> untyped

    def to_cartesian: () -> nil
  end
end
