module Autocad
  class TextNode < Element
    @ole_obj: untyped

    attr_reader original: untyped

    attr_reader ole_obj: untyped

    def to_regexp: () -> untyped

    def empty?: () -> untyped

    def text?: () -> false

    def size: () -> untyped

    def read_ole: (untyped ole) -> untyped

    def write_ole: (untyped text) -> untyped

    def write_ole_regular: (untyped text) -> untyped

    def write_ole_in_cell: (untyped text) -> untyped

    def update_ole!: (untyped text) -> untyped

    def to_s: () -> untyped

    def =~: (untyped reg) -> untyped

    def template?: () -> untyped

    def render: (?::Hash[untyped, untyped] h) -> self

    def method_missing: (untyped meth, *untyped) ?{ (?) -> untyped } -> untyped
  end
end
