name: CI

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # Weekly UI tests

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - run: bundle exec rake test

  ui_tests:
    needs: unit_tests
    runs-on: windows-latest # AutoCAD requires Windows
    if: github.event_name == 'schedule' # Only run on schedule
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1
          bundler-cache: true
      - run: bundle exec rake test:ui
